### PR TITLE
Popular movies

### PR DESCRIPTION
**Pull request by wsunkim**
popular movie data for 4 countries, 5 years with wiki plots

### CODE REVIEW

**Comment by soorajmr** [comment]
Thank you Wonsun. Could you please move the ipynb file into the notebooks subdirectory? It may be better to keep the csv data files in the dropbox shared directory unless version control is important for those files.

**Comment by wsunkim** [comment]
I'm sorry, Sooraj.

But, when I fork the github(sooraj/moviemeta) to my
repository(wsunkim/moviemeta), I could not find the folders.

The forked repository showed *.md files only. How can I fix this issue? I
don't know what the problem is..
I attached a screen shot of forked repository..please let me know if there
is any problem.

Sorry for the confusion.

Wonsun

2015-11-28 8:27 GMT-05:00 Sooraj Raveendran notifications@github.com:

> Thank you Wonsun. Could you please move the ipynb file into the notebooks
> subdirectory? It may be better to keep the csv data files in the dropbox
> shared directory unless version control is important for those files.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/soorajmr/moviemeta/pull/6#issuecomment-160296045.

## 

Won Sun Kim

Senior Researcher/Ph.D.

Korea Intellectual Property Strategy Institute

Email : wskim@kipsi.re.kr

Phone : +82-10-2042-1896

**Comment by wsunkim** [comment]
Thank you for your advice! Now I can see the notebook folders and move the ipynb into the 'notebook' folder. CSV files were uploaded on Dropbox and deleted from my forked repository. The ipynb was committed with comment "version1 of popular movies". Thank you so much!

**Comment by soorajmr** [comment]
Great. The pull request shows two versions of popular_movies.ipynb - one inside the notebooks directory and one outside. Please check whether you did a copy instead of move.

**Comment by wsunkim** [comment]
Yes, I copied the notebook. The two are same ones. Is it OK to delete the
outside one and commit again?

2015-11-28 10:07 GMT-05:00 Sooraj Raveendran notifications@github.com:

> Great. The pull request shows two versions of popular_movies.ipynb - one
> inside the notebooks directory and one outside. Please check whether you
> did a copy instead of move.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/soorajmr/moviemeta/pull/6#issuecomment-160308373.

## 

Won Sun Kim

Senior Researcher/Ph.D.

Korea Intellectual Property Strategy Institute

Email : wskim@kipsi.re.kr

Phone : +82-10-2042-1896

**Comment by soorajmr** [comment]
OK. In such cases, git mv is a better option. Now doing a git rm on the file outside should be the best option, I guess.

**Pull request merged**
